-- ============================================================
-- PREPNEST / Ji Sushi — idempotent schema (safe to re-run)
-- ============================================================

-- Menu items with "Item 86" toggle
CREATE TABLE IF NOT EXISTS menu_items (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  description TEXT,
  price NUMERIC(10,2) NOT NULL,
  category TEXT,
  image_url TEXT,
  is_available BOOLEAN DEFAULT TRUE
);

-- Backfill: add image_url to pre-existing databases (no-op if already present)
ALTER TABLE menu_items ADD COLUMN IF NOT EXISTS image_url TEXT;

-- Orders (dine-in vs takeaway)
CREATE TABLE IF NOT EXISTS orders (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  order_no INT GENERATED BY DEFAULT AS IDENTITY,
  customer_name TEXT,
  customer_phone TEXT,
  table_number INT,
  items JSONB NOT NULL,
  status TEXT DEFAULT 'pending',
  total_price NUMERIC(10,2),
  created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS pickup_minutes INT;

CREATE INDEX IF NOT EXISTS orders_status_idx ON orders(status);
CREATE INDEX IF NOT EXISTS orders_created_idx ON orders(created_at DESC);
CREATE INDEX IF NOT EXISTS menu_items_category_idx ON menu_items(category);

-- Loyalty program (phone = primary key)
CREATE TABLE IF NOT EXISTS loyalty_customers (
  phone TEXT PRIMARY KEY,
  name TEXT,
  stamps INT DEFAULT 0
);

-- Site theme / design settings (single row, JSONB). Managed from admin "Design" tab.
CREATE TABLE IF NOT EXISTS settings (
  id TEXT PRIMARY KEY,
  theme JSONB NOT NULL DEFAULT '{}'::jsonb
);
INSERT INTO settings (id, theme) VALUES ('main', '{}')
ON CONFLICT (id) DO NOTHING;
ALTER TABLE settings ADD COLUMN IF NOT EXISTS webhook_url TEXT;
ALTER TABLE settings ADD COLUMN IF NOT EXISTS webhook_secret TEXT;

-- Enable Realtime for instant KDS + menu updates
DO $$ BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE orders;
EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE menu_items;
EXCEPTION WHEN OTHERS THEN NULL; END $$;

-- RLS: allow the app (anon/publishable key) full access. MVP setup — tighten later.
ALTER TABLE menu_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE loyalty_customers ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS anon_all ON menu_items;
CREATE POLICY anon_all ON menu_items FOR ALL USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS anon_all ON orders;
CREATE POLICY anon_all ON orders FOR ALL USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS anon_all ON loyalty_customers;
CREATE POLICY anon_all ON loyalty_customers FOR ALL USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS anon_all ON settings;
CREATE POLICY anon_all ON settings FOR ALL USING (true) WITH CHECK (true);

-- ============================================================
-- Full Ji Sushi menu (98 items) — re-running will NOT duplicate
-- ============================================================
INSERT INTO menu_items (name, description, price, category) VALUES
('Edamame bønner', NULL, 45, 'Forretter'),
('Edamame bønner med chili', NULL, 50, 'Forretter'),
('Tangsalat', NULL, 55, 'Forretter'),
('Kimchi', NULL, 55, 'Forretter'),
('Wasabi bønner', NULL, 45, 'Forretter'),
('Rejechips', NULL, 39, 'Forretter'),
('Søde kartofler', NULL, 35, 'Forretter'),
('Sushi ris', NULL, 28, 'Forretter'),
('Vegetar forårsruller (5 stk.)', NULL, 40, 'Forretter'),
('Gyoza (5 stk.)', 'Grøntsager og svinekød', 50, 'Forretter'),
('Ebi fry (5 stk.)', NULL, 70, 'Forretter'),
('Kyllingefilet', NULL, 33, 'Sticks'),
('Oksekød', NULL, 38, 'Sticks'),
('Lam', NULL, 38, 'Sticks'),
('Kæmpe tigerreje', NULL, 35, 'Sticks'),
('Laks (spyd)', NULL, 35, 'Sticks'),
('Kylling kødboller', NULL, 30, 'Sticks'),
('Asparges med bacon', NULL, 35, 'Sticks'),
('Squash', NULL, 25, 'Sticks'),
('Laks Sashimi (6 skiver)', 'Serveres med ris', 85, 'Sashimi'),
('Tun Sashimi (6 skiver)', 'Serveres med ris', 89, 'Sashimi'),
('Sashimi Menu (12 skiver og 5 tigerrejer)', 'Serveres med ris', 205, 'Sashimi'),
('Tempura Rejer Tun Deluxe Roll (8 stk.)', 'Tempura rejer, avocado og agurk, toppet med tun og spicy mayo', 125, 'Toppet maki'),
('Tempura Rejer Grillet Laks Deluxe Roll (8 stk.)', 'Tempura rejer, avocado og mango, toppet med grillet laks og spicy mayo', 125, 'Toppet maki'),
('Tempura Rejer Avocado Deluxe Roll (8 stk.)', 'Tempura rejer, avocado og agurk, toppet med avocado og teriyaki', 125, 'Toppet maki'),
('Tempura Rejer Rainbow Deluxe Roll (8 stk.)', 'Tempura rejer, avocado og agurk, toppet med laks, tun, rejer, hvidfisk og bønnespirer', 125, 'Toppet maki'),
('Tempura Kylling Deluxe Roll (8 stk.)', 'Tempura kylling og agurk, toppet med avocado og spicy mayo', 120, 'Toppet maki'),
('Vegetar Deluxe Roll (8 stk.)', 'Salat mix, tofu, agurk og avocado, toppet med tangsalat og chili sesamfrø', 115, 'Toppet maki'),
('Grillet Laks Deluxe Roll (8 stk.)', 'Laks, avocado og agurk, toppet med grillet laks og forårsløg', 125, 'Toppet maki'),
('Laks Deluxe Roll (8 stk.)', 'Laks, avocado og agurk, toppet med laks og forårsløg', 125, 'Toppet maki'),
('Laks Avocado Deluxe Roll (8 stk.)', 'Laksemousse og tobiko, toppet med forårsløg og avocado', 120, 'Toppet maki'),
('Rainbow Roll (8 stk.)', 'Surimi, avocado og agurk, toppet med laks, rejer og hvidfisk', 120, 'Toppet maki'),
('Tun Avocado Deluxe Roll (8 stk.)', 'Tun og tobiko, toppet med tun og forårsløg', 120, 'Toppet maki'),
('Tempura Surimi Deluxe Roll (8 stk.)', 'Tempura surimi, avocado og agurk, toppet med bønnespirer', 120, 'Toppet maki'),
('Sesamfrø Ebi Tempura (8 stk.)', 'Ebi rejer, avocado, agurk og spicy sauce', 93, 'Uramaki'),
('San Francisco (8 stk.)', 'Laks, avocado, agurk, basilikum og ørredrogn', 90, 'Uramaki'),
('Super California (8 stk.)', 'Krebsehaler, avocado, agurk og tobiko', 90, 'Uramaki'),
('Alaska (8 stk.)', 'Laks, flødeost, avocado, agurk og tobiko', 90, 'Uramaki'),
('California (8 stk.)', 'Surimi, avocado, agurk og sesamfrø', 80, 'Uramaki'),
('Spicy Laks (8 stk.)', 'Surimi, avocado, agurk og sesamfrø', 83, 'Uramaki'),
('Spicy Rejer (8 stk.)', 'Tigerrejer, spicy sauce, agurk, avocado og sesamfrø', 85, 'Uramaki'),
('Spicy Tun (8 stk.)', 'Tun, spicy sauce, agurk, avocado og sesamfrø', 85, 'Uramaki'),
('Tigerrejer (8 stk.)', NULL, 53, 'Hosomaki'),
('Tun (8 stk.)', NULL, 50, 'Hosomaki'),
('Laks (8 stk.)', NULL, 50, 'Hosomaki'),
('Agurk (8 stk.)', NULL, 43, 'Hosomaki'),
('Avocado (8 stk.)', NULL, 43, 'Hosomaki'),
('Tun med avocado (8 stk.)', NULL, 53, 'Hosomaki'),
('Laks med avocado (8 stk.)', NULL, 53, 'Hosomaki'),
('Yami Ebi Rejer (5 stk.)', 'Ebi rejer, avocado og mango', 73, 'Futomaki'),
('Tempura Rejer (5 stk.)', 'Ebi rejer, avocado og agurk', 70, 'Futomaki'),
('Spicy Rejer (5 stk.)', 'Tigerrejer, avocado og agurk', 70, 'Futomaki'),
('Big Alaska (5 stk.)', 'Laks, flødeost, agurk, avocado og tobiko', 70, 'Futomaki'),
('California Laks (5 stk.)', 'Surimi, laks, avocado og agurk', 73, 'Futomaki'),
('Spicy Laks (5 stk.)', 'Laks, avocado og agurk', 70, 'Futomaki'),
('Spicy Tun (5 stk.)', 'Tun, agurk og avocado', 73, 'Futomaki'),
('California (5 stk.)', 'Surimi, avocado og agurk', 65, 'Futomaki'),
('Vegetar (5 stk.)', 'Avocado, agurk, tofu og salat mix', 60, 'Futomaki'),
('Laks', NULL, 22, 'Nigiri'),
('Grillet Laks', NULL, 24, 'Nigiri'),
('Laks med Avocado', NULL, 24, 'Nigiri'),
('Grillet Laks med Bønnespirer', NULL, 24, 'Nigiri'),
('Tun', NULL, 22, 'Nigiri'),
('Tun Tataki', NULL, 24, 'Nigiri'),
('Tun med Avocado', NULL, 24, 'Nigiri'),
('Tun med Forårsløg', NULL, 24, 'Nigiri'),
('Hvidfisk', NULL, 24, 'Nigiri'),
('Tigerrejer', NULL, 22, 'Nigiri'),
('Tigerrejer med Spicy Sauce', NULL, 24, 'Nigiri'),
('Krebsehaler', NULL, 27, 'Nigiri'),
('Laks Gunkan', NULL, 27, 'Nigiri'),
('Ørredrogn', NULL, 27, 'Nigiri'),
('Avocado', NULL, 20, 'Nigiri'),
('Agurk', NULL, 17, 'Nigiri'),
('Inari Tofu', NULL, 22, 'Nigiri'),
('Rispapir Laks (8 stk.)', 'Laks, salat mix, agurk og avocado med spicy sauce', 85, 'Rispapir ruller'),
('Rispapir Ebi Rejer (8 stk.)', 'Ebi rejer, salat mix, agurk og avocado med spicy sauce og teriyaki sauce', 85, 'Rispapir ruller'),
('Rispapir Tempura Kylling (8 stk.)', 'Tempura kylling, salat mix, agurk og avocado med spicy sauce og goma sauce', 85, 'Rispapir ruller'),
('Rispapir Oksekød (8 stk.)', 'Oksekød, salat mix, agurk og avocado med teriyaki sauce', 85, 'Rispapir ruller'),
('Goma dressing', NULL, 10, 'Tilbehør'),
('Hjemmelavet wasabi-mayo', NULL, 10, 'Tilbehør'),
('Hjemmelavet chili-mayo', NULL, 10, 'Tilbehør'),
('Hjemmelavet teriyaki', NULL, 10, 'Tilbehør'),
('Sød chilisauce', NULL, 10, 'Tilbehør'),
('Ebi Tempura Menu (24 stk.)', '8 deluxe ebi tempura rejer med avocado, 8 deluxe ebi tempura rejer med laks, 8 deluxe ebi tempura rejer med regnbue', 328, 'Menuer'),
('Nigiri Menu (8 stk.)', '2 laks, 2 laks med avocado, 2 grillet laks, 2 tun', 138, 'Menuer'),
('Uramaki Menu (32 stk.)', '8 ebi tempura rejer med sesamfrø, 8 laks deluxe roll, 8 rainbow roll, 8 Alaska roll', 388, 'Menuer'),
('Vegetar Menu (18 stk.)', '8 toppet maki: Vegetar Roll med avocado, 8 hosomaki: agurk, 2 nigiri: 1 tofu, 1 agurk', 168, 'Menuer'),
('10 Box (10 stk.)', '8 uramaki: ebi tempura rejer med sesamfrø, 2 nigiri: laks', 120, 'Sushi Box'),
('20 Box (20 stk.)', '8 uramaki: ebi tempura rejer med sesamfrø, 8 uramaki: spicy laks, 4 nigiri: 2 laks, 2 tun', 260, 'Sushi Box'),
('30 Box (30 stk.)', '8 uramaki: ebi tempura rejer med sesamfrø, 8 uramaki: spicy laks, 8 toppet maki: rainbow roll, 6 nigiri: 2 laks, 2 tun, 2 rejer', 360, 'Sushi Box'),
('40 Box (40 stk.)', '8 uramaki: California, 8 uramaki: Spicy laks, 8 toppet maki: ebi tempura rejer med avocado, 16 nigiri: 4 laks, 4 tun, 4 rejer, 4 grillet laks', 460, 'Sushi Box'),
('50 Box (50 stk.)', '8 uramaki: Spicy laks, 8 uramaki: California, 8 toppet maki: Ebi tempura rejer med avocado, 8 toppet maki: Laks deluxe roll, 18 nigiri: 4 laks, 4 tun, 4 rejer, 4 grillet laks, 2 avocado', 600, 'Sushi Box'),
('60 Box (60 stk.)', '8 uramaki: Spicy tun, 8 uramaki: Alaska, 8 toppet maki: Ebi tempura rejer med avocado, 8 toppet maki: Laks deluxe roll, 8 Rainbow roll, 20 nigiri: 5 laks, 5 tun, 5 rejer, 5 grillet laks', 700, 'Sushi Box'),
('70 Box (70 stk.)', '8 uramaki: Spicy tun, 8 uramaki: Alaska, 8 toppet maki: Ebi tempura med avocado, 8 toppet maki: Ebi tempura med laks, 8 toppet maki: Rainbow roll, 8 toppet maki: Laks deluxe roll, 22 nigiri: 5 laks, 5 tun, 5 rejer, 5 grillet laks, 2 krebsehaler', 820, 'Sushi Box'),
('80 Box (80 stk.)', '8 uramaki: Spicy tun, 8 uramaki: Alaska, 8 uramaki: California, 8 toppet maki: Ebi tempura med avocado, 8 toppet maki: Ebi tempura med laks, 8 toppet maki: Rainbow roll, 8 toppet maki: Laks deluxe roll, 24 nigiri: 5 laks, 5 tun, 5 rejer, 5 grillet laks, 4 krebsehaler', 950, 'Sushi Box'),
('Box 90 (90 stk.)', 'Sammensættes af sushikok', 1050, 'Sushi Box'),
('Box 100 (100 stk.)', 'Sammensættes af sushikok', 1200, 'Sushi Box'),
-- Super Tilbud: the 3 fixed takeaway combos, priced to match the site promo exactly
('Super Tilbud Menu 1 (36 stk.)', '8 nigiri (2 stk. af hver: rejer, laks, tun og flamberet laks), 6 futomaki med tempura rejer, 6 futomaki med tempura kylling, 8 Alaska med laks, 8 topping med tempurareje og flamberet laks', 300, 'Super Tilbud'),
('Super Tilbud Menu 2 (70 stk.)', '12 nigiri (3 stk. af hver: rejer, laks, tun og flamberet laks), 12 futomaki med tempura rejer, 6 futomaki med tempura kylling, 8 Alaska med laks, 8 spicy rejer, 8 topping med tempurareje og flamberet laks, 8 topping rainbow med surimi, 8 hosomaki med agurk', 530, 'Super Tilbud'),
('Super Tilbud Menu 3 (104 stk.)', '16 nigiri (4 stk. af hver: rejer, laks, tun og flamberet laks), 12 futomaki med tempura rejer, 12 futomaki med tempura kylling, 8 Alaska med laks, 8 flying chicken, 8 spicy rejer, 8 spicy tun, 8 topping med tempurareje og flamberet laks, 8 topping rainbow med surimi, 8 hosomaki med agurk, 8 hosomaki med laks', 750, 'Super Tilbud')
ON CONFLICT (name) DO NOTHING;
-- ---- Web Push subscriptions (kitchen iPad alerts) ----
CREATE TABLE IF NOT EXISTS push_subscriptions (
  endpoint TEXT PRIMARY KEY,
  keys JSONB NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE push_subscriptions ENABLE ROW LEVEL SECURITY;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'push_subscriptions' AND policyname = 'anon_all_push_subscriptions'
  ) THEN
    CREATE POLICY "anon_all_push_subscriptions" ON push_subscriptions FOR ALL
      USING (true) WITH CHECK (true);
  END IF;
END $$;
